[package]
name = "message-renderer"
description = "An example native yapi extension. Custom messages drawn by a message renderer."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
yapi-extension-api = { path = "../../yapi-extension-api", features = ["widgets"] }

[lints]
workspace = true
