[package]
name = "modal-editor"
description = "An example native yapi extension. A vim-like modal editor in place of the built-in one."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
yapi-extension-api = { path = "../../yapi-extension-api", features = ["widgets"] }

[lints]
workspace = true
