// @generated by `cargo xtask models` from @earendil-works/pi-ai 1.0.0. Do not edit.

/// When pi-ai generated the catalog data, as RFC 3339.
pub(crate) const GENERATED_AT: &str = "2026-10-01T18:57:11.882Z";

/// Built-in providers and their chat models as JSON arrays, by provider id.
pub(crate) const PROVIDERS: &[(&str, &str)] = &[
    (
        "amazon-bedrock",
        include_str!("../../data/amazon-bedrock.json"),
    ),
    ("ant-ling", include_str!("../../data/ant-ling.json")),
    ("anthropic", include_str!("../../data/anthropic.json")),
    (
        "azure-openai-responses",
        include_str!("../../data/azure-openai-responses.json"),
    ),
    ("baseten", include_str!("../../data/baseten.json")),
    ("cerebras", include_str!("../../data/cerebras.json")),
    (
        "cloudflare-ai-gateway",
        include_str!("../../data/cloudflare-ai-gateway.json"),
    ),
    (
        "cloudflare-workers-ai",
        include_str!("../../data/cloudflare-workers-ai.json"),
    ),
    ("deepseek", include_str!("../../data/deepseek.json")),
    ("fireworks", include_str!("../../data/fireworks.json")),
    (
        "github-copilot",
        include_str!("../../data/github-copilot.json"),
    ),
    ("google", include_str!("../../data/google.json")),
    (
        "google-vertex",
        include_str!("../../data/google-vertex.json"),
    ),
    ("groq", include_str!("../../data/groq.json")),
    ("huggingface", include_str!("../../data/huggingface.json")),
    ("kimi-coding", include_str!("../../data/kimi-coding.json")),
    ("meta", include_str!("../../data/meta.json")),
    ("minimax", include_str!("../../data/minimax.json")),
    ("minimax-cn", include_str!("../../data/minimax-cn.json")),
    ("mistral", include_str!("../../data/mistral.json")),
    ("moonshotai", include_str!("../../data/moonshotai.json")),
    (
        "moonshotai-cn",
        include_str!("../../data/moonshotai-cn.json"),
    ),
    ("nvidia", include_str!("../../data/nvidia.json")),
    ("openai", include_str!("../../data/openai.json")),
    ("openai-codex", include_str!("../../data/openai-codex.json")),
    ("opencode", include_str!("../../data/opencode.json")),
    ("opencode-go", include_str!("../../data/opencode-go.json")),
    ("openrouter", include_str!("../../data/openrouter.json")),
    (
        "qwen-token-plan",
        include_str!("../../data/qwen-token-plan.json"),
    ),
    (
        "qwen-token-plan-cn",
        include_str!("../../data/qwen-token-plan-cn.json"),
    ),
    (
        "qwen-token-plan-individual",
        include_str!("../../data/qwen-token-plan-individual.json"),
    ),
    ("radius", include_str!("../../data/radius.json")),
    ("together", include_str!("../../data/together.json")),
    ("typesafe", include_str!("../../data/typesafe.json")),
    (
        "vercel-ai-gateway",
        include_str!("../../data/vercel-ai-gateway.json"),
    ),
    ("xai", include_str!("../../data/xai.json")),
    ("xiaomi", include_str!("../../data/xiaomi.json")),
    (
        "xiaomi-token-plan-ams",
        include_str!("../../data/xiaomi-token-plan-ams.json"),
    ),
    (
        "xiaomi-token-plan-cn",
        include_str!("../../data/xiaomi-token-plan-cn.json"),
    ),
    (
        "xiaomi-token-plan-sgp",
        include_str!("../../data/xiaomi-token-plan-sgp.json"),
    ),
    ("zai", include_str!("../../data/zai.json")),
    (
        "zai-coding-cn",
        include_str!("../../data/zai-coding-cn.json"),
    ),
];

/// Classifier models as JSON arrays, by provider id.
pub(crate) const CLASSIFIERS: &[(&str, &str)] = &[
    (
        "cloudflare-workers-ai",
        include_str!("../../data/cloudflare-workers-ai.classifiers.json"),
    ),
    (
        "opencode",
        include_str!("../../data/opencode.classifiers.json"),
    ),
    (
        "openrouter",
        include_str!("../../data/openrouter.classifiers.json"),
    ),
    (
        "typesafe",
        include_str!("../../data/typesafe.classifiers.json"),
    ),
    (
        "vercel-ai-gateway",
        include_str!("../../data/vercel-ai-gateway.classifiers.json"),
    ),
];

/// Image-generation models as JSON arrays, by provider id.
pub(crate) const IMAGES: &[(&str, &str)] = &[(
    "openrouter",
    include_str!("../../data/openrouter.images.json"),
)];
