[package]
name = "select-menu"
description = "An example native yapi extension. A select list in a custom component."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
yapi-extension-api = { path = "../../yapi-extension-api", features = ["widgets"] }

[lints]
workspace = true
