//! `cargo xtask models`: generate the built-in model catalog from pi-ai's data.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};
use serde_json::Value;

use crate::read_json;

/// pi-ai release the catalog is generated from.
const PI_AI_VERSION: &str = "1.0.0";

/// Where the fixture generator's `npm ci` installs pi-ai.
const DEFAULT_SOURCE: &str = "tests/fixtures/pi/generator/node_modules/@earendil-works/pi-coding-agent/node_modules/@earendil-works/pi-ai";

/// Generate `crates/yapi-ai/data/*.json` and `crates/yapi-ai/src/catalog/data.rs` from
/// the chat, classifier and image models pi-ai ships in `dist/providers/data`.
///
/// Install the source first with `npm ci` in `tests/fixtures/pi/generator`.
#[derive(clap::Args)]
pub struct Args {
    /// Installed `@earendil-works/pi-ai` package directory.
    #[arg(long, default_value = DEFAULT_SOURCE)]
    source: PathBuf,
}

pub fn run(args: Args) -> anyhow::Result<()> {
    let package: Value = read_json(&args.source.join("package.json"))?;
    let version = package["version"].as_str().unwrap_or_default();
    if version != PI_AI_VERSION {
        bail!("expected pi-ai {PI_AI_VERSION}, found {version}");
    }

    let data_dir = args.source.join("dist/providers/data");
    let mut files: Vec<PathBuf> = fs::read_dir(&data_dir)
        .with_context(|| format!("reading {}", data_dir.display()))?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<_, _>>()?;
    files.retain(|path| {
        path.extension().is_some_and(|ext| ext == "json")
            && !path
                .file_name()
                .is_some_and(|name| name.to_string_lossy().starts_with('.'))
    });
    // By provider id, as pi lists them: `opencode` before `opencode-go`.
    files.sort_by_key(|path| path.file_stem().map(std::ffi::OsStr::to_os_string));

    let out_dir = Path::new("crates/yapi-ai/data");
    if out_dir.exists() {
        fs::remove_dir_all(out_dir)?;
    }
    fs::create_dir_all(out_dir)?;

    let mut table = String::new();
    let mut classifier_table = String::new();
    let mut image_table = String::new();
    let mut total = 0;
    let mut special = 0;
    for path in &files {
        let provider = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .context("provider file name")?;
        let groups: Value = read_json(path)?;
        let models = typed_models(&groups, "chat");
        let classifiers = typed_models(&groups, "classifier");
        let images = typed_models(&groups, "image");
        if models.is_empty() && classifiers.is_empty() && images.is_empty() {
            continue;
        }
        total += models.len();
        special += classifiers.len() + images.len();
        fs::write(
            out_dir.join(format!("{provider}.json")),
            json_lines(&models)?,
        )?;
        writeln!(
            table,
            "    (\"{provider}\", include_str!(\"../../data/{provider}.json\")),"
        )?;
        for (kind, list, table) in [
            ("classifiers", &classifiers, &mut classifier_table),
            ("images", &images, &mut image_table),
        ] {
            if list.is_empty() {
                continue;
            }
            fs::write(
                out_dir.join(format!("{provider}.{kind}.json")),
                json_lines(list)?,
            )?;
            writeln!(
                table,
                "    (\"{provider}\", include_str!(\"../../data/{provider}.{kind}.json\")),"
            )?;
        }
    }

    let manifest: Value = read_json(&data_dir.join(".manifest.json"))?;
    let generated_at = manifest["generatedAt"]
        .as_str()
        .context("generatedAt in the data manifest")?;
    let source = format!(
        "// @generated by `cargo xtask models` from @earendil-works/pi-ai {PI_AI_VERSION}. Do not edit.\n\
         \n\
         /// When pi-ai generated the catalog data, as RFC 3339.\n\
         pub(crate) const GENERATED_AT: &str = \"{generated_at}\";\n\
         \n\
         /// Built-in providers and their chat models as JSON arrays, by provider id.\n\
         pub(crate) const PROVIDERS: &[(&str, &str)] = &[\n{table}];\n\
         \n\
         /// Classifier models as JSON arrays, by provider id.\n\
         pub(crate) const CLASSIFIERS: &[(&str, &str)] = &[\n{classifier_table}];\n\
         \n\
         /// Image-generation models as JSON arrays, by provider id.\n\
         pub(crate) const IMAGES: &[(&str, &str)] = &[\n{image_table}];\n"
    );
    fs::write("crates/yapi-ai/src/catalog/data.rs", source)?;
    eprintln!(
        "wrote {total} chat models and {special} classifier and image models from {} providers",
        files.len()
    );
    Ok(())
}

/// Models of `kind` (`chat`, `classifier` or `image`) in pi's catalog order: by
/// API group, then by entry. Models without a type are chat models.
fn typed_models(groups: &Value, kind: &str) -> Vec<Value> {
    let Some(groups) = groups.as_object() else {
        return Vec::new();
    };
    groups
        .values()
        .filter_map(Value::as_object)
        .flat_map(|models| models.values())
        .filter(|model| model["type"].as_str().unwrap_or("chat") == kind)
        .cloned()
        .collect()
}

/// A JSON array with one model per line.
fn json_lines(models: &[Value]) -> anyhow::Result<String> {
    let mut json = String::from("[\n");
    for (index, model) in models.iter().enumerate() {
        json += &yapi_types::json::to_string(model)?;
        json += if index + 1 < models.len() {
            ",\n"
        } else {
            "\n"
        };
    }
    json += "]\n";
    Ok(json)
}
