//! `cargo xtask models`: generate the built-in model catalog from pi-ai's data.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, bail};
use serde_json::Value;

/// pi-ai release the catalog is generated from.
const PI_AI_VERSION: &str = "1.0.0";

/// Where the fixture generator's `npm ci` installs pi-ai.
const DEFAULT_SOURCE: &str = "tests/fixtures/pi/generator/node_modules/@earendil-works/pi-coding-agent/node_modules/@earendil-works/pi-ai";

/// Generate `crates/ri-ai/data/*.json` and `crates/ri-ai/src/catalog/data.rs` from
/// the chat models pi-ai ships in `dist/providers/data`.
///
/// Install the source first with `npm ci` in `tests/fixtures/pi/generator`.
#[derive(clap::Args)]
pub struct Args {
    /// Installed `@earendil-works/pi-ai` package directory.
    #[arg(long, default_value = DEFAULT_SOURCE)]
    source: PathBuf,
}

pub fn run(args: Args) -> anyhow::Result<()> {
    let package: Value = read_json(&args.source.join("package.json"))?;
    let version = package["version"].as_str().unwrap_or_default();
    if version != PI_AI_VERSION {
        bail!("expected pi-ai {PI_AI_VERSION}, found {version}");
    }

    let data_dir = args.source.join("dist/providers/data");
    let mut files: Vec<PathBuf> = fs::read_dir(&data_dir)
        .with_context(|| format!("reading {}", data_dir.display()))?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<Result<_, _>>()?;
    files.retain(|path| {
        path.extension().is_some_and(|ext| ext == "json")
            && !path
                .file_name()
                .is_some_and(|name| name.to_string_lossy().starts_with('.'))
    });
    files.sort();

    let out_dir = Path::new("crates/ri-ai/data");
    if out_dir.exists() {
        fs::remove_dir_all(out_dir)?;
    }
    fs::create_dir_all(out_dir)?;

    let mut table = String::new();
    let mut total = 0;
    for path in &files {
        let provider = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .context("provider file name")?;
        let models = chat_models(&read_json(path)?);
        if models.is_empty() {
            continue;
        }
        total += models.len();
        let mut json = String::from("[\n");
        for (index, model) in models.iter().enumerate() {
            json += &ri_types::json::to_string(model)?;
            json += if index + 1 < models.len() {
                ",\n"
            } else {
                "\n"
            };
        }
        json += "]\n";
        fs::write(out_dir.join(format!("{provider}.json")), json)?;
        writeln!(
            table,
            "    (\"{provider}\", include_str!(\"../../data/{provider}.json\")),"
        )?;
    }

    let source = format!(
        "// @generated by `cargo xtask models` from @earendil-works/pi-ai {PI_AI_VERSION}. Do not edit.\n\
         \n\
         /// Built-in providers and their chat models as JSON arrays, by provider id.\n\
         pub(crate) const PROVIDERS: &[(&str, &str)] = &[\n{table}];\n"
    );
    fs::write("crates/ri-ai/src/catalog/data.rs", source)?;
    eprintln!("wrote {total} chat models from {} providers", files.len());
    Ok(())
}

/// Chat models in pi's catalog order: by API group, then by entry.
fn chat_models(groups: &Value) -> Vec<Value> {
    let Some(groups) = groups.as_object() else {
        return Vec::new();
    };
    groups
        .values()
        .filter_map(Value::as_object)
        .flat_map(|models| models.values())
        .filter(|model| model["type"].as_str().is_none_or(|kind| kind == "chat"))
        .cloned()
        .collect()
}

fn read_json(path: &Path) -> anyhow::Result<Value> {
    let text = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}
